# Generated by Django 3.0.8 on 2020-07-16 20:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Titulo',
            fields=[
                ('universidad_id', models.AutoField(primary_key=True, serialize=False)),
                ('universitarios', models.IntegerField()),
                ('titulo_obtenido', models.TextField()),
                ('posgrado', models.TextField()),
                ('teologicos', models.TextField()),
                ('estado', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='EstudioRealizado',
            fields=[
                ('estudiorealizado_id', models.AutoField(primary_key=True, serialize=False)),
                ('primaria', models.IntegerField()),
                ('secundaria', models.IntegerField()),
                ('estado', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
