# Generated by Django 3.0.8 on 2020-07-08 04:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('iglesia', '0001_initial'),
        ('seccion', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Destacamento',
            fields=[
                ('destacamento_id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=250)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='destacamento/imagenes')),
                ('distrito', models.CharField(max_length=250)),
                ('numero', models.IntegerField(unique=True)),
                ('estado', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('iglesia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='iglesia.Iglesia')),
                ('seccion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='seccion.Seccion')),
            ],
        ),
    ]
