# Generated by Django 3.0.8 on 2020-07-16 20:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('eps', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Perfil',
            fields=[
                ('perfil_id', models.AutoField(primary_key=True, serialize=False)),
                ('foto', models.ImageField(blank=True, null=True, upload_to='perfil/imagenes')),
                ('identificacion', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('tipo_identificacion', models.CharField(choices=[('A+', 'A+'), ('B+', 'B+'), ('O+', 'O+'), ('AB+', 'AB+'), ('A-', 'A-'), ('B-', 'B-'), ('O-', 'O-'), ('AB-', 'AB-')], max_length=10)),
                ('fecha_nacimiento', models.DateField(verbose_name='Fecha Nacimiento')),
                ('lugar_nacimiento', models.CharField(max_length=250)),
                ('genero', models.CharField(choices=[('Hombre', 'Hombre'), ('Mujer', 'Mujer')], max_length=10)),
                ('tipo_sangre', models.CharField(choices=[('A+', 'A+'), ('B+', 'B+'), ('O+', 'O+'), ('AB+', 'AB+'), ('A-', 'A-'), ('B-', 'B-'), ('O-', 'O-'), ('AB-', 'AB-')], max_length=3)),
                ('direccion', models.CharField(max_length=100)),
                ('telefono', models.CharField(max_length=100)),
                ('celular', models.CharField(max_length=100)),
                ('profesion', models.CharField(blank=True, max_length=200, null=True)),
                ('estado_civil', models.CharField(blank=True, choices=[('Casado(a)', 'Casado(a)'), ('Soltero(a)', 'Soltero(a)'), ('Viudo(a)', 'Viudo(a)'), ('Separado(a)', 'Separado(a)'), ('Divorciado(a)', 'Divorciado(a)')], max_length=50, null=True)),
                ('anion_conversion', models.CharField(blank=True, max_length=10, null=True)),
                ('bautismo_agua', models.BooleanField(default=True)),
                ('bautismo_espiritu', models.BooleanField(default=True)),
                ('estado', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('eps', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eps.Eps')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
