# Generated by Django 3.0.8 on 2020-07-19 02:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('destacamento', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil',
            name='Destacamento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='destacamento.Destacamento'),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='tipo_identificacion',
            field=models.CharField(choices=[('Cc', 'Cc'), ('Ti', 'Ti'), ('Rc', 'Rc'), ('Otros', 'Otros')], max_length=10),
        ),
    ]
