# Generated by Django 3.0.8 on 2020-07-13 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grupos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grupos',
            name='nombre',
            field=models.CharField(max_length=150, unique=True),
        ),
    ]
