# Generated by Django 3.0.8 on 2020-07-13 02:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('destacamento', '0001_initial'),
        ('grupos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GrupoDestacamento',
            fields=[
                ('grupodestacamento_id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('destacamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='destacamento.Destacamento')),
                ('dgrupo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='grupos.Grupos')),
            ],
        ),
    ]
